package:
  name: totptray
  version: 1.2.2

source:
  git_rev:
  git_url: https://github.com/McCzarny/totptray

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/McCzarny/totptray
